# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6096da6b971920ddac6b52f9360d67dbb841aad92de629264737db8f34c044cc98e11f7cb6f193118c600239dd7d3692c33121094bf8b950b9e856985285727

test:
  secret_key_base: f3812b53906046def66c29880950f6c033b434cdeb748ef1caf5a9ed2257fab15a422b34a5b7b7d71dd5db3606cfda0a04d84d63a2b880f3df03bf06f467d5dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
